# Generated by Django 4.2.3 on 2023-07-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0002_alter_wishlist_unique_together_remove_wishlist_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(default='www.'),
        ),
    ]
