# Generated by Django 4.2.3 on 2023-07-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='remaining_day',
            field=models.IntegerField(default=15),
        ),
    ]
