# Generated by Django 4.2.3 on 2023-07-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_borrow_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='remaining_day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
