# Generated by Django 4.2.3 on 2023-07-19 19:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_management', '0003_book_image_url'),
        ('transaction', '0006_alter_borrow_remaining_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrow',
            unique_together={('user', 'book')},
        ),
    ]
