# Generated by Django 4.2.3 on 2023-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_borrow_is_already_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
    ]
