# Generated by Django 4.2.3 on 2023-07-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_borrow_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
