# Generated by Django 4.2.3 on 2023-07-20 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0003_book_image_url'),
        ('transaction', '0010_alter_borrow_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='book_management.book'),
        ),
    ]
