# Generated by Django 4.2.4 on 2023-11-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_alter_borrow_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='fine',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
