# Generated by Django 4.2.7 on 2023-11-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_remove_borrow_remaining_day_alter_borrow_borrow_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateWaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=55)),
                ('store_pass', models.CharField(max_length=55)),
            ],
        ),
    ]
