# Generated by Django 4.2.7 on 2023-11-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_paymentgatewaysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
