# Generated by Django 4.2.7 on 2023-12-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_alter_borrow_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgatewaysettings',
            options={'verbose_name': 'PaymentGateWaySetting', 'verbose_name_plural': 'PaymentGateWaySettings'},
        ),
        migrations.AlterUniqueTogether(
            name='borrow',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Walet',
        ),
    ]
